const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..');const html=fs.readFileSync(path.join(root,'outputs/immune-frontline.html'),'utf8');const script=html.match(/<script>([\s\S]*)<\/script>/)[1];const engine=script.split('\nconst $=s=>document')[0]+'\n})();';const context={window:{}};vm.runInNewContext(engine,context);const {Battle,MISSIONS}=context.window.ImmuneGame;
const clone=b=>{const c=Object.create(Battle.prototype);Object.assign(c,b);c.s=JSON.parse(JSON.stringify(b.s));return c};
let b=new Battle('flu','standard',['dc','cd8','bcell']);let before=b.snapshot();assert.equal(b.act('cd8').report.killed,0,'naive CD8 must not kill');b=new Battle('flu','standard',['dc','cd8','bcell']);b.act('present');assert.equal(b.s.adaptive,false);b.act('antibody');assert.equal(b.s.adaptive,false);assert.equal(b.act('cd8').report.killed,2);assert.equal(b.s.adaptive,true);assert(b.s.cells.some(c=>!c.alive),'CD8 must leave dead host cells');assert(b.s.logs.length===3,'round log must persist');
b=new Battle('pneumo');assert.equal(b.act('mac').report.cleared,0,'MAC must not clear Gram-positive pneumococcus');b=new Battle('meningo');assert.equal(b.act('mac').report.cleared,4,'MAC must clear susceptible Neisseria');
b=new Battle('tb');const inside=b.counts().inside;b.act('gamma');assert.equal(b.active(b.s.gammaUntil),false,'naive Th1 must not activate macrophages');b=new Battle('tb');b.act('present');b.act('hold');b.act('gamma');const n=b.counts().inside;b.act('phago');assert(b.counts().inside<n,'activated macrophages must clear intracellular bacteria');
b=new Battle('flu','standard',['dc','cd8','bcell']);b.act('present');b.act('ifn');b.act('produce');assert.equal(b.s.plasma,true);assert(b.s.ab>1,'plasma cells must replenish antibodies');
b=new Battle('pneumo');before=JSON.stringify(b.s);b.snapshot();b.counts();b.actions();assert.equal(JSON.stringify(b.s),before,'read-only/idle access must not advance the simulation');
b=new Battle('pneumo');b.s.ab=0;before=JSON.stringify(b.s);assert.equal(b.act('antibody').accepted,false);assert.equal(JSON.stringify(b.s),before,'rejected actions must not consume a turn');
function score(b){const s=b.s,c=b.counts();return -c.outside*2-c.inside*3-c.infected*5+s.health*.04+(s.adaptive?7:0)+(s.plasma?8:0)+(b.active(s.c3bUntil)&&b.m.capsule?5:0)+(b.active(s.il17Until)&&b.mission==='candida'?8:0)+(b.active(s.gammaUntil)&&b.mission==='tb'?12:0)+(b.active(s.ifnUntil)&&b.mission==='flu'?6:0)+s.contained*14}
function key(b){const s=b.s,c=b.counts();return JSON.stringify([c,s.health,s.cells.filter(c=>c.alive).length,s.primingAt,s.adaptive,s.plasma,s.ab,s.c3bUntil,s.abUntil,s.ifnUntil,s.gammaUntil,s.il17Until,s.macReady,s.recruited,s.contained])}
function winPath(m,d){let beam=[{b:new Battle(m,d,MISSIONS[m].defaults,77),path:[]}];for(let depth=0;depth<24;depth++){let candidates=[];const seen=new Set();for(const item of beam)for(const a of item.b.actions()){const next=clone(item.b),r=next.act(a.id);if(!r.accepted)continue;const p=item.path.concat(a.id);if(next.s.won)return p;if(next.s.done)continue;const k=key(next);if(seen.has(k))continue;seen.add(k);candidates.push({b:next,path:p,score:score(next)})}candidates.sort((a,b)=>b.score-a.score);beam=candidates.slice(0,85);if(!beam.length)break}return null}
let failures=[];for(const m of Object.keys(MISSIONS))for(const d of ['easy','standard','hard']){const p=winPath(m,d);if(!p){failures.push(m+'/'+d);console.log('UNWINNABLE: '+m+'/'+d)}else console.log(`${m}/${d}: ${p.join(' > ')}`)}
for(const m of Object.keys(MISSIONS)){const fail=new Battle(m,'standard');while(!fail.s.done)fail.act('hold');assert.equal(fail.s.won,false,`${m}: indecision over repeated turns must permit failure`)}
assert.equal(failures.length,0,'Unwinnable missions: '+failures.join(', '));console.log('PASS: all 15 mission/difficulty combinations, activation, targeting compartments, tissue consequences, persistent logs and idle invariants.');
