const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const folder=path.resolve(__dirname,'../outputs/versions'),records=JSON.parse(fs.readFileSync(path.join(folder,'manifest.json'),'utf8'));
const nav=fs.readFileSync(path.join(folder,'navigation.js'),'utf8'),player=fs.readFileSync(path.join(folder,'play.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
class El{constructor(){this.children=[];this.style={};this.listeners={};this.value='';this.innerHTML='';}append(c){this.children.push(c);if(this.value==='')this.value=c.value}replaceChildren(...c){this.children=c;this.value=(c.find(x=>x.selected)||c[0]).value}addEventListener(t,f){this.listeners[t]=f}}
function state(href){const u=new URL(href),els=new Map([['#version',new El()],['#game',new El()],['#latest',new El()],['#archive',new El()]]);let inserted=0;const body={style:{},prepend(){inserted++}};const doc={title:'',currentScript:{src:'https://sces5504.github.io/immune-frontline/versions/navigation.js',dataset:{}},body,querySelector:s=>els.get(s),createElement(){const e=new El();e.attachShadow=()=>({innerHTML:'',querySelector:s=>els.get(s)});return e}};return {els,doc,inserted:()=>inserted,location:{href:u.href,search:u.search,protocol:u.protocol},history:{replaceState(a,b,url){this.url=String(url)}}}}
(async()=>{for(const record of records){const s=state('https://sces5504.github.io/immune-frontline/versions/'+record.file);s.doc.currentScript.dataset.version=record.version;let fetched;
 vm.runInNewContext(nav,{document:s.doc,location:s.location,URL,URLSearchParams,fetch:async u=>{fetched=String(u);return {ok:true,json:async()=>records}}});await new Promise(setImmediate);
 assert.equal(s.inserted(),1);assert.equal(s.els.get('#version').value,record.version);assert.equal(s.els.get('#version').children.length,records.length);assert.equal(fetched,'https://sces5504.github.io/immune-frontline/versions/manifest.json');assert.equal(s.els.get('#latest').href,'https://sces5504.github.io/immune-frontline/versions/play.html?version='+records.at(-1).version+'&catalog='+records.at(-1).version);
 s.els.get('#version').value=records.at(-1).version;s.els.get('#version').listeners.change();assert(s.location.href.endsWith('play.html?version='+records.at(-1).version+'&catalog='+records.at(-1).version));}
 for(const protocol of ['https:','file:']){const url=protocol==='file:'?'file:///workspace/outputs/versions/play.html?version=1.0.0':'https://sces5504.github.io/immune-frontline/versions/play.html?version=1.0.0';const s=state(url);vm.runInNewContext(player,{document:s.doc,location:s.location,history:s.history,URL,URLSearchParams});assert.equal(s.els.get('#game').src,'v1.0.0.html?embedded=1');s.els.get('#version').value=records.at(-1).version;s.els.get('#version').onchange();assert.equal(s.els.get('#game').src,records.at(-1).file+'?embedded=1');assert(s.history.url.includes('version='+records.at(-1).version));s.els.get('#version').value='1.0.0';s.els.get('#version').onchange();s.els.get('#latest').onclick({preventDefault(){}});assert.equal(s.els.get('#game').src,records.at(-1).file+'?embedded=1');if(protocol==='file:')assert.equal(s.els.get('#latest').href,'../immune-frontline.html')}
 const embedded=state('https://sces5504.github.io/immune-frontline/versions/v1.0.0.html?embedded=1');vm.runInNewContext(nav,{document:embedded.doc,location:embedded.location,URL,URLSearchParams});assert.equal(embedded.inserted(),0,'the iframe must not duplicate the outer version toolbar');assert.equal(embedded.els.get('#archive').target,'_top','archive links must leave the player frame rather than create nested players');
 console.log('PASS: every released version can return to latest or select any other version; local archive playback and embedded toolbar isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
