"""Shared navigation is added to published copies, keeping release snapshots immutable."""
import html,json
from pathlib import Path
NAV_JS = r'''(()=>{'use strict';if(new URLSearchParams(location.search).get('embedded')==='1'){const archive=document.querySelector('#archive');if(archive)archive.target='_top';return;}
const script=document.currentScript,base=new URL('.',script.src),current=script.dataset.version;
const host=document.createElement('div');host.id='immune-version-navigation';host.style.cssText='position:fixed;inset:0 0 auto 0;z-index:2147483000';
const shadow=host.attachShadow({mode:'open'});shadow.innerHTML=`<style>:host{font:13px/1.4 -apple-system,sans-serif;color:#efe5ce}*{box-sizing:border-box}.bar{height:46px;background:#111b2b;border-bottom:2px solid #3f5964;display:flex;align-items:center;justify-content:center;gap:14px;padding:5px 12px;box-shadow:0 3px 0 #080d17}label{font-weight:700;white-space:nowrap}select{font:inherit;max-width:300px;background:#23374c;color:#f4e8cf;border:1px solid #6bd5bc;padding:5px 7px}a{color:#83e0c8;text-decoration:none;white-space:nowrap}a:focus-visible,select:focus-visible{outline:2px solid #f0cb7a;outline-offset:2px}@media(max-width:600px){.bar{gap:9px;font-size:11px}select{max-width:145px}label{display:none}}</style><nav class="bar" aria-label="遊戲版本切換"><label for="version">切換版本</label><select id="version" aria-label="選擇遊戲版本"><option>v${current}</option></select><a id="latest">回到新版 ↗</a><a id="archive">版本檔案室</a></nav>`;
document.body.prepend(host);document.body.style.paddingTop='46px';shadow.querySelector('#archive').href=new URL('index.html',base).href;shadow.querySelector('#latest').href=new URL('../index.html',base).href;
fetch(new URL('manifest.json',base)).then(r=>{if(!r.ok)throw Error('version list unavailable');return r.json()}).then(records=>{shadow.querySelector('#latest').href=new URL('play.html?version='+encodeURIComponent(records[records.length-1].version),base).href;const select=shadow.querySelector('#version');select.replaceChildren(...records.slice().reverse().map(r=>{const o=document.createElement('option');o.value=r.version;o.textContent='v'+r.version+' · '+r.title;o.selected=r.version===current;return o}));select.addEventListener('change',()=>{location.href=new URL('play.html?version='+encodeURIComponent(select.value),base).href})}).catch(()=>{shadow.querySelector('#version').disabled=true});})();'''
STYLE='''*{box-sizing:border-box}body{margin:0;background:#12182b;color:#f1eadc;font:16px/1.7 -apple-system,sans-serif}main{max-width:980px;margin:auto;padding:48px 24px}h1{font-size:32px}p,small{color:#a6b5c7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}article{padding:24px;border:2px solid #34435b;background:#1a2539;box-shadow:5px 5px 0 #070c19}h2{font-size:19px}.version{color:#5bdfc7;font-weight:800}a{display:block;color:#5bdfc7;text-decoration:none;font-weight:bold;margin-top:18px}nav a{display:inline-block;margin:0}'''
def write_pages(folder,records):
    folder=Path(folder)
    cards='\n'.join(f'<article><div class="version">v{html.escape(x["version"])}</div><h2>{html.escape(x["title"])}</h2><p>{html.escape(x["notes"])}</p><small>{html.escape(x["date"])} · 獨立版本備份</small><a href="play.html?version={html.escape(x["version"])}">玩這個版本 →</a></article>' for x in reversed(records))
    index='''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>免疫前線｜版本檔案室</title><style>'''+STYLE+'''</style><main><nav><a href="../index.html" id="latest">← 回到新版</a></nav><h1>版本檔案室</h1><p>選一版開始遊玩；遊戲上方都有版本選單，可以直接換回新版。切換版本會重新開始該版遊戲。</p><div class="grid">'''+cards+'''</div><p>如要把主要上線版本還原，可在 GitHub Actions 的部署流程填入版本號，或請我還原指定版本。</p></main><script>if(location.protocol==='file:')document.querySelector('#latest').href='../immune-frontline.html';</script></html>'''
    index=index.replace('href="../index.html" id="latest"', 'href="play.html?version='+records[-1]['version']+'" id="latest"')
    folder.joinpath('index.html').write_text(index)
    data=json.dumps(records,ensure_ascii=False).replace('</','<\\/')
    player='''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>免疫前線｜切換版本</title><style>*{box-sizing:border-box}html,body{margin:0;height:100%;background:#111b2b;color:#efe5ce;font:13px -apple-system,sans-serif}nav{height:54px;display:flex;align-items:center;justify-content:center;gap:14px;padding:6px 10px;border-bottom:2px solid #3f5964}select{max-width:360px;font:inherit;background:#23374c;color:#f4e8cf;border:1px solid #6bd5bc;padding:7px}a{color:#83e0c8;text-decoration:none;white-space:nowrap}iframe{width:100%;height:calc(100% - 54px);border:0;display:block}a:focus-visible,select:focus-visible{outline:2px solid #f0cb7a;outline-offset:2px}@media(max-width:600px){nav{gap:9px;font-size:11px}select{max-width:155px}label{display:none}}</style></head><body><nav aria-label="遊戲版本切換"><label for="version">切換版本</label><select id="version" aria-label="選擇遊戲版本"></select><a id="latest" href="../index.html">回到新版 ↗</a><a href="index.html">版本檔案室</a></nav><iframe id="game" title="免疫前線遊戲" allow="fullscreen"></iframe><script>
const records='''+data+''';const select=document.querySelector('#version'),frame=document.querySelector('#game');for(const r of records.slice().reverse()){const o=document.createElement('option');o.value=r.version;o.textContent='v'+r.version+' · '+r.title;select.append(o)}const requested=new URLSearchParams(location.search).get('version');select.value=records.some(r=>r.version===requested)?requested:records[records.length-1].version;
function load(){const record=records.find(r=>r.version===select.value);frame.src=record.file+'?embedded=1';document.title='免疫前線 v'+record.version;const url=new URL(location.href);url.searchParams.set('version',record.version);try{history.replaceState(null,'',url)}catch{} }select.onchange=load;document.querySelector('#latest').onclick=(event)=>{event.preventDefault();select.value=records[records.length-1].version;load()};if(location.protocol==='file:')document.querySelector('#latest').href='../immune-frontline.html';load();
</script></body></html>'''
    folder.joinpath('play.html').write_text(player)
    folder.joinpath('navigation.js').write_text(NAV_JS+'\n')

def decorate_game(content,version,script_path):
    insertion='<script data-version="'+html.escape(version,quote=True)+'" src="'+html.escape(script_path,quote=True)+'"></script>'
    return content.replace('</body>',insertion+'</body>')
